typography issue solved
danielschuster-muc/potter-db pull request #217
Opened 2022-10-07 16:55 UTC by chintan0513

- [ ] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [ ] Bug fix ()
## _Improved error of typography_

## Before
![Screenshot (7)](https://user-images.githubusercontent.com/64206626/194608248-98ccdc72-d37f-4077-b200-a7bcc4c93d85.png)

## After
![Screenshot (8)](https://user-images.githubusercontent.com/64206626/194608487-77b8927c-5039-43c3-b87f-c9329e5df05b.png)

## Summary
Added CSS property in Link tag

2022-10-07 17:09 UTC, danielschuster-muc commented
Thank you for your PR. Adding the `textDecoration: none` is definitely much better. 

As you are currently working on the Navbar, could you maybe change the icon to the [potter db icon](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/public/android-chrome-192x192.png)? 
For that I would suggest converting the image to svg and importing the svg with the [next/image](https://nextjs.org/docs/api-reference/next/image) component. 

And can you please check the checkboxes in the pr description.

2022-10-07 17:15 UTC, chintan0513 commented
Thank you for your response. 

Sure, I would be happy to work on this portion as well as react part.

Check ✔️

2022-10-07 17:17 UTC, danielschuster-muc commented
Great, thank you!

2022-10-07 19:32 UTC, chintan0513 commented
Icon*

2022-10-07 19:50 UTC, danielschuster-muc requested changes
I think you need to add the icon itself.

2022-10-08 08:49 UTC, danielschuster-muc requested changes
Can you please change the icon to [this one](https://github.com/danielschuster-muc/potter-db/blob/master/frontend/public/android-chrome-192x192.png) by converting it to a svg icon?

2022-10-08 11:09 UTC, danielschuster-muc commented
No, it was fine how it was, just replace the `images/logo.svg` icon, which you added and is currently a broomstick, with [this icon](https://github.com/danielschuster-muc/potter-db/blob/master/logo.svg). And leave the rest as it was before [this commit](https://github.com/danielschuster-muc/potter-db/pull/217/commits/61fb04d673678e3299dd1cadf189b988383a0667).

2022-10-08 13:42 UTC, danielschuster-muc requested changes
Please just **copy** the icon located on https://github.com/danielschuster-muc/potter-db/blob/master/logo.svg. 
And don't move or rename any files like frontend/public/android-chrome-12x192.png.

2022-10-08 13:42 UTC, danielschuster-muc commented on frontend/next.config.js
> +    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
This is not required.

2022-10-08 13:42 UTC, danielschuster-muc commented on frontend/src/components/layout/Navbar.js
> +          <Image src="/images/logo.svg" width={30} height={10} alt="logo" />
why do you have a different width and height for a square icon?

2022-10-08 17:26 UTC, danielschuster-muc requested changes
Looks good so far. 
But you accidentially renamed `android-chrome-192x192.png` to `android-chrome-12x192.png`.

2022-10-08 17:30 UTC, chintan0513 commented
What about now?

2022-10-08 17:32 UTC, chintan0513 commented
Sure I'll try and let you know

2022-10-08 17:34 UTC, danielschuster-muc requested changes
No, don't delete `frontend/public/android-chrome-192x192.png`, it's important.

2022-10-08 17:55 UTC, danielschuster-muc approved these changes
Everything looks good! Thank you for contributing to Potter DB.

2022-10-08 17:56 UTC, merged