Create placeholders
danielschuster-muc/potter-db pull request #220
Opened 2022-10-08 09:01 UTC by eduardconstantin

- [ ] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [ ] Bug fix (please link related issues if applicable)
- [ ] New feature (either for website or api)
- [ ] Database improvement
- [x] Other

## Summary

- Create wizard placeholder to be used in characters page

2022-10-08 18:16 UTC, danielschuster-muc requested changes
Those images are just awesome! Good job! 

Can you just pull from origin/master, so that you can also implement the image for the spells.
And could you rename the images to **missing_*type***?

2022-10-08 19:28 UTC, eduardconstantin commented
Thank you! Sure, I'll make the changes.

2022-10-08 20:10 UTC, danielschuster-muc requested changes

2022-10-08 20:10 UTC, danielschuster-muc commented on frontend/src/components/pages/characters/CharacterListItem.js
> +            src={image || "/images/missing_wizard.svg"}
```suggestion
            src={image || "/images/missing_character.svg"}
```

2022-10-09 08:49 UTC, danielschuster-muc requested changes
You should probably also rename the `missing_wizard.svg` file to `missing_character.svg`.

2022-10-09 08:58 UTC, eduardconstantin commented
oh, in the script, right

2022-10-09 09:10 UTC, danielschuster-muc approved these changes
Everything‘s good now! Thank you for your contribution and those awesome images!

2022-10-09 09:11 UTC, eduardconstantin commented
You're welcome! Glad I could help!

2022-10-09 09:11 UTC, merged