Feat/book pages
danielschuster-muc/potter-db pull request #241
Opened 2022-10-11 17:58 UTC by eduardconstantin

- [x] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [ ] Bug fix (please link related issues if applicable)
- [x] New feature (either for website or api)
- [ ] Database improvement
- [ ] Other

## Summary

- Create book pages

2022-10-11 20:05 UTC, danielschuster-muc requested changes

2022-10-11 20:11 UTC, eduardconstantin commented on frontend/src/components/pages/books/BookListItem.js
> +          <ListItemBox value={pages} icon={faClock} />
Sure, I forgot about the icons

2022-10-11 20:45 UTC, danielschuster-muc requested changes

2022-10-11 20:45 UTC, danielschuster-muc commented on frontend/src/components/pages/index/SearchBar.js
> +  const [searchType, setSearchType] = useState("chapters");
```suggestion
  const [searchType, setSearchType] = useState("characters");
```

2022-10-13 08:15 UTC, danielschuster-muc requested changes
Just some small changes.

2022-10-13 08:15 UTC, danielschuster-muc commented on frontend/src/lib/utils.js
> +  "harry-potter-and-the-deathly-hallows": "#51476a"
Can you change the colors for the 1st and 6th book? Those are really hard to see. Maybe a bit lighter version of the 2 colors are better

2022-10-13 08:15 UTC, danielschuster-muc commented on frontend/src/lib/utils.js
> +export const getBookColor = {
```suggestion
export const getBookColorBySlug = {
```

2022-10-13 08:15 UTC, danielschuster-muc commented on frontend/src/lib/utils.js
> +  "harry-potter-and-the-deathly-hallows": "#51476a"
And can you also put the whole method in a switch statement? Wwith a default color, if the slug doesn't match.

2022-10-13 08:15 UTC, danielschuster-muc commented on frontend/src/components/pages/books/BookList.js
> +            : 0}
```suggestion
        totalResults={rawBooks?.meta?.pagination?.records || 0}
```
This should fix the results count.

2022-10-13 08:15 UTC, danielschuster-muc commented on frontend/src/lib/utils.js
> +  "harry-potter-and-the-deathly-hallows": "#51476a"
And don't forget to change it in other places, too.

2022-10-14 19:17 UTC, danielschuster-muc approved these changes
Thank you for the changes, looks good now!

2022-10-14 19:17 UTC, merged

2022-10-14 19:27 UTC, eduardconstantin commented
Great! You're welcome!