Add sitemap generator
danielschuster-muc/potter-db pull request #256
Opened 2022-10-19 08:33 UTC by differentreality

- [ ] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [X] New feature (either for website or **api**)

## Summary

Add sitemap https://github.com/danielschuster-muc/potter-db/issues/221 

* Add `sitemap_generator` gem
* Add relevant config file `config/sitemap.rb`
  * with entries for books, characters, movies, potions, and spells index paths
* Update robots file

The generated sitemap in `public/sitemap.xml.gz`

![Screenshot from 2022-10-19 11-30-29](https://user-images.githubusercontent.com/4322737/196639105-21ff4f0e-16ed-42a8-883c-ccddad0f505f.png)

2022-10-20 12:59 UTC, danielschuster-muc requested changes
Thank you for your contribution to Potter DB. Can you please implement the request changes?

2022-10-21 18:52 UTC, differentreality commented on backend/config/sitemap.rb
> +
Yep that makes sense

2022-10-21 18:57 UTC, danielschuster-muc approved these changes
Looks good. Thank you for your contribution!

2022-10-21 19:03 UTC, merged

2022-10-27 08:16 UTC, differentreality commented
@danielschuster-muc do you think it makes sense to add a cron job (eg see https://github.com/javan/whenever) in order to refresh the sitemap every X time period?

2022-10-27 13:06 UTC, danielschuster-muc commented
We actually don’t need this as the Sitemap only contains static / non-dynamic generated pages. And those pages won’t change.