Add Slovak translations
danielschuster-muc/potter-db pull request #773
Opened 2023-10-16 18:05 UTC by romana-la

## Summary

Translation of the documentation into Slovak language.

## Related Issues

Is part of #738

## Checklist

- [x] This pull request has a meaningful title and description.
- [x] I have read and followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).
- [x] My code follows the conventions and coding style of this project.
- [x] All tests pass and I have added tests for my changes 
- [ ] I have updated necessary documentation

2023-10-16 20:30 UTC, danielschuster-muc requested changes
Thanks for your contribution! Looks pretty good so far. Just some smaller things, see my comments.

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/index.sk.mdx
> +- získať podrobné informácie o knihách (`books`) a filmoch (`movies`) zo sveta Harryho Pottera
It's nice that you added the english translation / key of the resources here.

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources.sk.mdx
> +    title="Knihy (books)"
I am not quite sure if the english translations are needed here.

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources.sk.mdx
> +    title="Knihy (books)"
I mean it's not bad to have, but what do you think, is it needed to understand it?

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources/_meta.sk.json
> +}
same here

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources/chapters.sk.mdx
> +# Kapitoly (chapters)
also here and on the other pages, do we really need the english translation of the resource keys?

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/apis/graphql.sk.mdx
> +Vďaka GraphQL môžete získať presne tie dáta, ktoré potrebujete. Dopyty musia obsahovať polia, o ktoré máte záujem, a vzťahy medzi nimi. Napríklad:
```suggestion
## Dopytovanie dát

Vďaka GraphQL môžete získať presne tie dáta, ktoré potrebujete. Dopyty musia obsahovať polia, o ktoré máte záujem, a vzťahy medzi nimi. Napríklad:
```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/apis/graphql.sk.mdx
> +Kompletnú schému GraphQL API nájdete [tu](https://github.com/danielschuster-muc/potter-db/blob/master/backend/app/graphql/schema.json).
```suggestion
## Schéma

Kompletnú schému GraphQL API nájdete [tu](https://github.com/danielschuster-muc/potter-db/blob/master/backend/app/graphql/schema.json).
```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/apis/rest.sk.mdx
> +## Formát JSON:API
```suggestion
## Formát JSON:API

```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/getting-started.sk.mdx
> +# REST vs. GraphQL
```suggestion
# REST vs. GraphQL

```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/getting-started.sk.mdx
> +## Obmedzenie maximálneho počtu požiadaviek
```suggestion
## Obmedzenie maximálneho počtu požiadaviek

```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources/chapters.sk.mdx
> +# Kapitoly (chapters)
```suggestion
# Kapitoly (chapters)

```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources/potions.sk.mdx
> +# Odvary (potions)
```suggestion
# Odvary (potions)

```

2023-10-16 20:30 UTC, danielschuster-muc commented on docs/pages/resources/spells.sk.mdx
> +# Zaklínadlá (spells)
```suggestion
# Zaklínadlá (spells)

```

2023-10-24 17:51 UTC, danielschuster-muc commented
Hi @romana-la, are there any updates from your side? Could you please resolve the requested changed, so I can merge you pr?

2023-10-25 20:16 UTC, romana-la commented
Hi @danielschuster-muc, thanks for your feedback and sorry that it took me so long to get to it. I have implemented most of your suggestions. Re. having resources in both English and Slovak - I have dropped English from the statistics table but I would still keep it in the table of contents and titles. When somebody makes a request, they will have to specify the resource in the request URL in English. When they then look in the documentation for the explanation of attributes to interpret the response, they will be likely looking for the English word.

2023-10-26 11:50 UTC, danielschuster-muc commented
> Hi @danielschuster-muc, thanks for your feedback and sorry that it took me so long to get to it. I have implemented most of your suggestions. Re. having resources in both English and Slovak - I have dropped English from the statistics table but I would still keep it in the table of contents and titles. When somebody makes a request, they will have to specify the resource in the request URL in English. When they then look in the documentation for the explanation of attributes to interpret the response, they will be likely looking for the English word.

Yes, you definitely have a point, makes sense to have the resources names in English and Slovak. Thank you for your input.

2023-10-26 11:51 UTC, danielschuster-muc approved these changes
Looks very nice! Thanks for your contribution.

2023-10-26 20:55 UTC, merged

2023-10-27 15:09 UTC, kolja-lucht commented
Hey @danielschuster-muc 
could provide the German translation 🧙‍♀️

2023-10-28 15:56 UTC, danielschuster-muc commented
> Hey @danielschuster-muc could provide the German translation 🧙‍♀️

sure! maybe you can leave a short note in #738

2023-10-28 16:26 UTC, kolja-lucht commented
Oops, I thought I had commented on that issue. Didn't realize I was in a PR 😅 Sorry about that @danielschuster-muc