Translations added: Portuguese (Brazil)
danielschuster-muc/potter-db pull request #785
Opened 2023-10-23 14:30 UTC by cnfranco

I translate the documentation to Portuguese (Brazil).

2023-10-24 17:31 UTC, danielschuster-muc commented
This PR doesn't seem to be finished.

2023-10-30 21:40 UTC, danielschuster-muc commented
Can I help you with anything @cnfranco?

2023-10-31 17:05 UTC, cnfranco commented
> This PR doesn't seem to be finished.

Yes, it wasn't finished, but I added the latest translations throughout this week. However, I am unable to correct the following check error (image attached).

![potter](https://github.com/danielschuster-muc/potter-db/assets/126128193/294fb919-79d1-4668-bc0e-9a5e0697aecc)

Could you see what could be causing this?

2023-10-31 18:04 UTC, danielschuster-muc commented
> > This PR doesn't seem to be finished.
> 
> Yes, it wasn't finished, but I added the latest translations throughout this week. However, I am unable to correct the following check error (image attached).
> 
> ![potter](https://user-images.githubusercontent.com/126128193/279457891-294fb919-79d1-4668-bc0e-9a5e0697aecc.png)
> 
> Could you see what could be causing this?


<html>
<body>
<!--StartFragment-->

Failed to compile.
--
17:12:17.916 |  
17:12:17.917 | ./theme.config.tsx:99:190
17:12:17.917 | Type error: Property assignment expected.
17:12:17.917 |  
17:12:17.917 | 97 \|     </>
17:12:17.917 | 98 \|   ),
17:12:17.917 | >  99 \|   i18n: [{ locale: "en", text: "English" }, { locale: "fr", text: "Français" }, { locale: "es", text: "Español" }, { locale: "sk", text: "Slovenčina" }, { locale: "de", text: "Deutsch" }], { locale: "pt", text: "Português" }],
17:12:17.918 | \|                                                                                                                                                                                              ^
17:12:17.918 | 100 \|   logo: <span>Potter DB: Docs</span>,
17:12:17.918 | 101 \|   project: {
17:12:17.918 | 102 \|     link: "https://github.com/danielschuster-muc/potter-db",
17:12:17.959 | Error: Command "npm run build" exited with 1

<!--EndFragment-->
</body>
</html>

Seems to be an issue with the theme.config.tsx.

2023-10-31 18:06 UTC, danielschuster-muc commented on docs/theme.config.tsx
> +  i18n: [{ locale: "en", text: "English" }, { locale: "fr", text: "Français" }, { locale: "es", text: "Español" }, { locale: "sk", text: "Slovenčina" }, { locale: "de", text: "Deutsch" }], { locale:
```suggestion
  i18n: [{ locale: "en", text: "English" }, { locale: "fr", text: "Français" }, { locale: "es", text: "Español" }, { locale: "sk", text: "Slovenčina" }, { locale: "de", text: "Deutsch" }, { locale: "pt", text: "Português" }],
``` 
This should probably fix it @cnfranco

2023-10-31 20:46 UTC, cnfranco commented
@danielschuster-muc, can you please review?

2023-10-31 22:01 UTC, danielschuster-muc requested changes
Looks quite good so far. On mayor thing: please always add an empty line below headers / subheaders. 
Looking forward to seeing the other missing pages.

2023-10-31 22:01 UTC, danielschuster-muc commented on docs/pages/apis/rest.pt.mdx
> +Você pode ordenar recursos adicionando um parâmetro `sort` da query à sua solicitação. Por exemplo, para ordenar personagens pelo nome, você pode usar o atributo `name` (vá para [Recursos](#resources
```suggestion
Você pode ordenar recursos adicionando um parâmetro `sort` da query à sua solicitação. Por exemplo, para ordenar personagens pelo nome, você pode usar o atributo `name` (vá para [Recursos](/resources) para ver todos os atributos disponíveis):
```

2023-10-31 22:02 UTC, danielschuster-muc commented on docs/pages/index.pt.mdx
> +- Explorar uma lista abrangente de `feitiços`e `poções`usadas no mundo mágico.
```suggestion
- Explorar uma lista abrangente de `feitiços` e `poções` usadas no mundo mágico.
```

2023-10-31 22:23 UTC, cnfranco commented on docs/pages/getting-started.pt.mdx
> +_Agora que você conhece o básico, vamos mergulhar na documentação da API para explorar endpoints disponíveis e começar a elaborar suas consultas mágicas. Refira-se a seção de documentação para [REST]
Done.

2023-10-31 22:24 UTC, cnfranco commented on docs/pages/resources.pt.mdx
> +# Resources Overview
Done.

2023-10-31 22:39 UTC, cnfranco commented on docs/pages/index.pt.mdx
> +- Conseguir
Done.

2023-11-01 11:29 UTC, danielschuster-muc requested changes
Please always add an empty line after the Headers. 
E.g.:

```
# Title

and here comes the text after one empty line
```

Also don't forget to translate the resource pages for books, chapter, characters etc.

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/getting-started.pt.mdx
> +# REST vs. GraphQL
empty line after it

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/getting-started.pt.mdx
> +## Technical details
same here

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/getting-started.pt.mdx
> +## Limitação de taxa
and here

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/index.pt.mdx
> +## O que é Potter DB: API?
here

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/index.pt.mdx
> +## Estatística
here

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/apis/graphql.pt.mdx
> +## Esboço
empty line after heading pls

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/apis/graphql.pt.mdx
> +## GraphQL Endpoint
Could you please always add empty lines after the headings

2023-11-01 11:29 UTC, danielschuster-muc commented on docs/pages/apis/graphql.pt.mdx
> +GraphQL permite solicitar precisamente os dados que você precisa. Para construir uma query, especifique os campos que você quer recuperar e seus relacionamentos. Por exemplo:
also here

2023-12-18 02:15 UTC, cnfranco commented
> Please always add an empty line after the Headers. E.g.:
> 
> ```
> # Title
> 
> and here comes the text after one empty line
> ```
> 
> Also don't forget to translate the resource pages for books, chapter, characters etc.

Done.

2023-12-30 19:25 UTC, danielschuster-muc commented
> Also don't forget to translate the resource pages for books, chapter, characters etc.

2024-02-25 20:25 UTC, danielschuster-muc requested changes
Resources sub pages are still missing

2024-05-09 16:59 UTC, closed without merging